development:
  sessions:
    default:
      database: cypress_development
      hosts:
        - 54.152.244.137:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: cypress_test
      hosts:
        - <%= ENV['TEST_DB_HOST'] || 'localhost' %>:27017
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: cypress_production
      hosts:
        - 54.152.244.137:27017
  options:
    raise_not_found_error: false

measure_eval:
  sessions:
    default:
      database: cypress_measure_eval
      hosts:
        - 54.152.244.137:27017
  options:
    raise_not_found_error: false

